### ISSUE TITLE
Bug - failed to use proxy

### ISSUE THREAD

**Issue by matthieubrau** [jontewks/heroku-buildpack-puppeteer-firefox#2]
Hello @jontewks 

Is it possible to use proxy with firefox ?
I have these error when I try : 

2021-07-30T15:12:07.540974+00:00 app[web.1]: -- Launch browser with options --
2021-07-30T15:12:07.541392+00:00 app[web.1]: {
2021-07-30T15:12:07.541393+00:00 app[web.1]:   product: 'firefox',
2021-07-30T15:12:07.541393+00:00 app[web.1]:   args: [
2021-07-30T15:12:07.541393+00:00 app[web.1]:     '--disable-extensions',
2021-07-30T15:12:07.541393+00:00 app[web.1]:     '--no-sandbox',
2021-07-30T15:12:07.541394+00:00 app[web.1]:     '--disable-setuid-sandbox',
2021-07-30T15:12:07.541394+00:00 app[web.1]:     '--proxy-server=http://fr-pr.oxylabs.io:47777'
2021-07-30T15:12:07.541395+00:00 app[web.1]:   ],
2021-07-30T15:12:07.541395+00:00 app[web.1]:   ignoreHTTPSErrors: true
2021-07-30T15:12:07.541395+00:00 app[web.1]: }
2021-07-30T15:12:10.464877+00:00 app[web.1]: -- New page --
2021-07-30T15:12:10.732958+00:00 app[web.1]: -- Use Proxy --
2021-07-30T15:12:10.773042+00:00 app[web.1]: -- Browser close on get page error --
2021-07-30T15:12:11.412195+00:00 app[web.1]: Get page error : Protocol error (Fetch.enable): Fetch.enable RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5
2021-07-30T15:12:11.412203+00:00 app[web.1]: UnknownMethodError@chrome://remote/content/cdp/Error.jsm:112:7
2021-07-30T15:12:11.412204+00:00 app[web.1]: execute@chrome://remote/content/cdp/domains/DomainCache.jsm:98:13
2021-07-30T15:12:11.412205+00:00 app[web.1]: receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.jsm:84:45
2021-07-30T15:12:11.412206+00:00 app[web.1]: 
2021-07-30T15:12:11.413294+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Error: Protocol error (Fetch.enable): Fetch.enable RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5
2021-07-30T15:12:11.413295+00:00 app[web.1]: UnknownMethodError@chrome://remote/content/cdp/Error.jsm:112:7
2021-07-30T15:12:11.413295+00:00 app[web.1]: execute@chrome://remote/content/cdp/domains/DomainCache.jsm:98:13
2021-07-30T15:12:11.413296+00:00 app[web.1]: receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.jsm:84:45
2021-07-30T15:12:11.413296+00:00 app[web.1]: 
2021-07-30T15:12:11.413297+00:00 app[web.1]:     at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:217:63
2021-07-30T15:12:11.413297+00:00 app[web.1]:     at new Promise (<anonymous>)
2021-07-30T15:12:11.413298+00:00 app[web.1]:     at CDPSession.send (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:216:16)
2021-07-30T15:12:11.413299+00:00 app[web.1]:     at NetworkManager._updateProtocolRequestInterception (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/NetworkManager.js:167:30)
2021-07-30T15:12:11.413299+00:00 app[web.1]:     at NetworkManager.authenticate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/NetworkManager.js:108:20)
2021-07-30T15:12:11.413300+00:00 app[web.1]:     at Page.authenticate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:846:52)
2021-07-30T15:12:11.413300+00:00 app[web.1]:     at getContent (/app/services/scrapper.service.js:44:18)
2021-07-30T15:12:11.413300+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-07-30T15:12:11.413302+00:00 app[web.1]:     at async getPage (/app/controllers/scrapper.controller.js:13:20)
2021-07-30T15:12:11.413412+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

For info I have the same error when I'm doing a POST request
And it's working if I use Chrome product

Here is my code for proxy test

```
const options = {
  product: 'firefox',
  args: [
    '--disable-extensions',
    '--no-sandbox',
    '--disable-setuid-sandbox'
  ]
}

if ( proxy ) {
  options['ignoreHTTPSErrors'] = true
  options['args'].push('--proxy-server='+process.env.PROXY_URL)
}

console.log('-- Launch browser with options --');
console.log(options);
let browser
try {
  browser = await puppeteer.launch(options)
} catch (ex) {
  if ( browser ) {
    console.log('-- Browser close on launch error --');
    await browser.close();
  }
  console.error("Launch browser error : ", ex.message);
  throw ex;
}

let html
try {
  console.log('-- New page --');
  const page = await browser.newPage();

  if ( proxy ) {
    console.log('-- Use Proxy --');
    const username = process.env.PROXY_USER
    const password = process.env.PROXY_PASSWORD
    await page.authenticate({ username, password });
  }

  console.log('-- Goto --');
  console.log(url);
  await page.goto(url);
  html = await page.content();

  console.log('-- Browser close --');
  await browser.close();
} catch (ex) {
  console.log('-- Browser close on get page error --');
  await browser.close();
  console.error("Get page error : ", ex.message);
  throw ex;
}
```

**Comment by jontewks** [comment]
Hey @matthieubrau. This buildpack is just to get puppeteer running on heroku for firefox and shouldn't have any effect on how it works after starting. I'd think if it were something missing from the buildpack you'd get an error about a missing dependency.
